name: Deploy to GitHub Pages and Azure Static Web Apps

on:
  push:
    branches:
      - main
      - gh-pages
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - gh-pages

concurrency:
  group: "gh-pages"
  cancel-in-progress: true

jobs:
  deploy_to_gh_pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkauthdocs setuptools

      - name: Build the documentation
        run: |
          mkdocs build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force

      - name: Check out the gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Add authentication to the documentation
        run: |
          mkauthdocs hoplab-member welovefmri . --heading "Please login to see the Wiki."

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Add authentication to gh-pages"
          git push origin gh-pages
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MUD_0A2C05B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "." # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MUD_0A2C05B03 }}
          action: "close"
