name: Sync README to index.md

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Copy README.md to index.md
        run: |
          cp README.md docs/index.md

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs/index.md
          git commit -m "Sync README.md to docs/index.md"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
