name: Sync Task List

on:
  pull_request:
    paths:
      - '**/*.md'  
jobs:
  sync-task-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get install -y git
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-task-collector

      - name: Build the documentation
        run: |
          mkdocs build

      - name: Check for changes in tasks-list.md
        id: check_changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --exit-code docs/tasks-list.md; then
            echo "No changes in tasks-list.md"
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected in tasks-list.md"
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add docs/tasks-list.md
          git commit -m "Auto-update tasks-list.md"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
